# Generated by Django 4.1.7 on 2024-02-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
